server:
  port: 5050

spring:
  application:
    name: marketgg-client

  datasource:
    url: jdbc:mysql://127.0.0.1/index
    username: root
    password: 1234

  profiles:
    include: oauth2, redis

marketgg:
  gateway-origin: http://localhost:6060

redis:
  url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/mcXcTmrnbRezlila/secrets/ae33d69450f841cfa1d5cce5250746f4
  password-url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/mcXcTmrnbRezlila/secrets/42c84798d4784e83be3c568a75809829
